name: Library Management System CI

on:
  push:
    # branches: [ main ]  Runs on every branch if not specified

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    # - name: Create virtual environment
    #   run: |
    #     python -m venv venv
    #     source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run test cases
      run: |
        pytest